// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: stellar/v1/token_transfers.proto

package stellarv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TokenTransferEventMeta contains metadata about a token transfer event.
type TokenTransferEventMeta struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LedgerSequence   uint32                 `protobuf:"varint,1,opt,name=ledger_sequence,json=ledgerSequence,proto3" json:"ledger_sequence,omitempty"`
	ClosedAt         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	TxHash           string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TransactionIndex uint32                 `protobuf:"varint,4,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	OperationIndex   *uint32                `protobuf:"varint,5,opt,name=operation_index,json=operationIndex,proto3,oneof" json:"operation_index,omitempty"`
	ContractAddress  string                 `protobuf:"bytes,6,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	InSuccessfulTx   bool                   `protobuf:"varint,7,opt,name=in_successful_tx,json=inSuccessfulTx,proto3" json:"in_successful_tx,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenTransferEventMeta) Reset() {
	*x = TokenTransferEventMeta{}
	mi := &file_stellar_v1_token_transfers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenTransferEventMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenTransferEventMeta) ProtoMessage() {}

func (x *TokenTransferEventMeta) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_v1_token_transfers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenTransferEventMeta.ProtoReflect.Descriptor instead.
func (*TokenTransferEventMeta) Descriptor() ([]byte, []int) {
	return file_stellar_v1_token_transfers_proto_rawDescGZIP(), []int{0}
}

func (x *TokenTransferEventMeta) GetLedgerSequence() uint32 {
	if x != nil {
		return x.LedgerSequence
	}
	return 0
}

func (x *TokenTransferEventMeta) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

func (x *TokenTransferEventMeta) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TokenTransferEventMeta) GetTransactionIndex() uint32 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

func (x *TokenTransferEventMeta) GetOperationIndex() uint32 {
	if x != nil && x.OperationIndex != nil {
		return *x.OperationIndex
	}
	return 0
}

func (x *TokenTransferEventMeta) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *TokenTransferEventMeta) GetInSuccessfulTx() bool {
	if x != nil {
		return x.InSuccessfulTx
	}
	return false
}

// Asset represents a Stellar asset.
type Asset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Asset:
	//
	//	*Asset_Native
	//	*Asset_Issued
	//	*Asset_ContractId
	Asset         isAsset_Asset `protobuf_oneof:"asset"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_stellar_v1_token_transfers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_v1_token_transfers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_stellar_v1_token_transfers_proto_rawDescGZIP(), []int{1}
}

func (x *Asset) GetAsset() isAsset_Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *Asset) GetNative() bool {
	if x != nil {
		if x, ok := x.Asset.(*Asset_Native); ok {
			return x.Native
		}
	}
	return false
}

func (x *Asset) GetIssued() *IssuedAsset {
	if x != nil {
		if x, ok := x.Asset.(*Asset_Issued); ok {
			return x.Issued
		}
	}
	return nil
}

func (x *Asset) GetContractId() string {
	if x != nil {
		if x, ok := x.Asset.(*Asset_ContractId); ok {
			return x.ContractId
		}
	}
	return ""
}

type isAsset_Asset interface {
	isAsset_Asset()
}

type Asset_Native struct {
	Native bool `protobuf:"varint,1,opt,name=native,proto3,oneof"`
}

type Asset_Issued struct {
	Issued *IssuedAsset `protobuf:"bytes,2,opt,name=issued,proto3,oneof"`
}

type Asset_ContractId struct {
	ContractId string `protobuf:"bytes,3,opt,name=contract_id,json=contractId,proto3,oneof"`
}

func (*Asset_Native) isAsset_Asset() {}

func (*Asset_Issued) isAsset_Asset() {}

func (*Asset_ContractId) isAsset_Asset() {}

type IssuedAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetCode     string                 `protobuf:"bytes,1,opt,name=asset_code,json=assetCode,proto3" json:"asset_code,omitempty"`
	AssetIssuer   string                 `protobuf:"bytes,2,opt,name=asset_issuer,json=assetIssuer,proto3" json:"asset_issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuedAsset) Reset() {
	*x = IssuedAsset{}
	mi := &file_stellar_v1_token_transfers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuedAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuedAsset) ProtoMessage() {}

func (x *IssuedAsset) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_v1_token_transfers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuedAsset.ProtoReflect.Descriptor instead.
func (*IssuedAsset) Descriptor() ([]byte, []int) {
	return file_stellar_v1_token_transfers_proto_rawDescGZIP(), []int{2}
}

func (x *IssuedAsset) GetAssetCode() string {
	if x != nil {
		return x.AssetCode
	}
	return ""
}

func (x *IssuedAsset) GetAssetIssuer() string {
	if x != nil {
		return x.AssetIssuer
	}
	return ""
}

type Transfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Asset         *Asset                 `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_stellar_v1_token_transfers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_v1_token_transfers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_stellar_v1_token_transfers_proto_rawDescGZIP(), []int{3}
}

func (x *Transfer) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Transfer) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Transfer) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *Transfer) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type Mint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Asset         *Asset                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mint) Reset() {
	*x = Mint{}
	mi := &file_stellar_v1_token_transfers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mint) ProtoMessage() {}

func (x *Mint) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_v1_token_transfers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mint.ProtoReflect.Descriptor instead.
func (*Mint) Descriptor() ([]byte, []int) {
	return file_stellar_v1_token_transfers_proto_rawDescGZIP(), []int{4}
}

func (x *Mint) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Mint) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *Mint) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type Burn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Asset         *Asset                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Burn) Reset() {
	*x = Burn{}
	mi := &file_stellar_v1_token_transfers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Burn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Burn) ProtoMessage() {}

func (x *Burn) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_v1_token_transfers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Burn.ProtoReflect.Descriptor instead.
func (*Burn) Descriptor() ([]byte, []int) {
	return file_stellar_v1_token_transfers_proto_rawDescGZIP(), []int{5}
}

func (x *Burn) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Burn) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *Burn) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type Clawback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Asset         *Asset                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Clawback) Reset() {
	*x = Clawback{}
	mi := &file_stellar_v1_token_transfers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Clawback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clawback) ProtoMessage() {}

func (x *Clawback) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_v1_token_transfers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clawback.ProtoReflect.Descriptor instead.
func (*Clawback) Descriptor() ([]byte, []int) {
	return file_stellar_v1_token_transfers_proto_rawDescGZIP(), []int{6}
}

func (x *Clawback) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Clawback) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *Clawback) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type Fee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Asset         *Asset                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fee) Reset() {
	*x = Fee{}
	mi := &file_stellar_v1_token_transfers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fee) ProtoMessage() {}

func (x *Fee) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_v1_token_transfers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fee.ProtoReflect.Descriptor instead.
func (*Fee) Descriptor() ([]byte, []int) {
	return file_stellar_v1_token_transfers_proto_rawDescGZIP(), []int{7}
}

func (x *Fee) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Fee) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *Fee) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type TokenTransferEvent struct {
	state protoimpl.MessageState  `protogen:"open.v1"`
	Meta  *TokenTransferEventMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*TokenTransferEvent_Transfer
	//	*TokenTransferEvent_Mint
	//	*TokenTransferEvent_Burn
	//	*TokenTransferEvent_Clawback
	//	*TokenTransferEvent_Fee
	Event         isTokenTransferEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenTransferEvent) Reset() {
	*x = TokenTransferEvent{}
	mi := &file_stellar_v1_token_transfers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenTransferEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenTransferEvent) ProtoMessage() {}

func (x *TokenTransferEvent) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_v1_token_transfers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenTransferEvent.ProtoReflect.Descriptor instead.
func (*TokenTransferEvent) Descriptor() ([]byte, []int) {
	return file_stellar_v1_token_transfers_proto_rawDescGZIP(), []int{8}
}

func (x *TokenTransferEvent) GetMeta() *TokenTransferEventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TokenTransferEvent) GetEvent() isTokenTransferEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TokenTransferEvent) GetTransfer() *Transfer {
	if x != nil {
		if x, ok := x.Event.(*TokenTransferEvent_Transfer); ok {
			return x.Transfer
		}
	}
	return nil
}

func (x *TokenTransferEvent) GetMint() *Mint {
	if x != nil {
		if x, ok := x.Event.(*TokenTransferEvent_Mint); ok {
			return x.Mint
		}
	}
	return nil
}

func (x *TokenTransferEvent) GetBurn() *Burn {
	if x != nil {
		if x, ok := x.Event.(*TokenTransferEvent_Burn); ok {
			return x.Burn
		}
	}
	return nil
}

func (x *TokenTransferEvent) GetClawback() *Clawback {
	if x != nil {
		if x, ok := x.Event.(*TokenTransferEvent_Clawback); ok {
			return x.Clawback
		}
	}
	return nil
}

func (x *TokenTransferEvent) GetFee() *Fee {
	if x != nil {
		if x, ok := x.Event.(*TokenTransferEvent_Fee); ok {
			return x.Fee
		}
	}
	return nil
}

type isTokenTransferEvent_Event interface {
	isTokenTransferEvent_Event()
}

type TokenTransferEvent_Transfer struct {
	Transfer *Transfer `protobuf:"bytes,2,opt,name=transfer,proto3,oneof"`
}

type TokenTransferEvent_Mint struct {
	Mint *Mint `protobuf:"bytes,3,opt,name=mint,proto3,oneof"`
}

type TokenTransferEvent_Burn struct {
	Burn *Burn `protobuf:"bytes,4,opt,name=burn,proto3,oneof"`
}

type TokenTransferEvent_Clawback struct {
	Clawback *Clawback `protobuf:"bytes,5,opt,name=clawback,proto3,oneof"`
}

type TokenTransferEvent_Fee struct {
	Fee *Fee `protobuf:"bytes,6,opt,name=fee,proto3,oneof"`
}

func (*TokenTransferEvent_Transfer) isTokenTransferEvent_Event() {}

func (*TokenTransferEvent_Mint) isTokenTransferEvent_Event() {}

func (*TokenTransferEvent_Burn) isTokenTransferEvent_Event() {}

func (*TokenTransferEvent_Clawback) isTokenTransferEvent_Event() {}

func (*TokenTransferEvent_Fee) isTokenTransferEvent_Event() {}

type TokenTransferBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*TokenTransferEvent  `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenTransferBatch) Reset() {
	*x = TokenTransferBatch{}
	mi := &file_stellar_v1_token_transfers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenTransferBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenTransferBatch) ProtoMessage() {}

func (x *TokenTransferBatch) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_v1_token_transfers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenTransferBatch.ProtoReflect.Descriptor instead.
func (*TokenTransferBatch) Descriptor() ([]byte, []int) {
	return file_stellar_v1_token_transfers_proto_rawDescGZIP(), []int{9}
}

func (x *TokenTransferBatch) GetEvents() []*TokenTransferEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_stellar_v1_token_transfers_proto protoreflect.FileDescriptor

const file_stellar_v1_token_transfers_proto_rawDesc = "" +
	"\n" +
	" stellar/v1/token_transfers.proto\x12\n" +
	"stellar.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd7\x02\n" +
	"\x16TokenTransferEventMeta\x12'\n" +
	"\x0fledger_sequence\x18\x01 \x01(\rR\x0eledgerSequence\x127\n" +
	"\tclosed_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12+\n" +
	"\x11transaction_index\x18\x04 \x01(\rR\x10transactionIndex\x12,\n" +
	"\x0foperation_index\x18\x05 \x01(\rH\x00R\x0eoperationIndex\x88\x01\x01\x12)\n" +
	"\x10contract_address\x18\x06 \x01(\tR\x0fcontractAddress\x12(\n" +
	"\x10in_successful_tx\x18\a \x01(\bR\x0einSuccessfulTxB\x12\n" +
	"\x10_operation_index\"\x80\x01\n" +
	"\x05Asset\x12\x18\n" +
	"\x06native\x18\x01 \x01(\bH\x00R\x06native\x121\n" +
	"\x06issued\x18\x02 \x01(\v2\x17.stellar.v1.IssuedAssetH\x00R\x06issued\x12!\n" +
	"\vcontract_id\x18\x03 \x01(\tH\x00R\n" +
	"contractIdB\a\n" +
	"\x05asset\"O\n" +
	"\vIssuedAsset\x12\x1d\n" +
	"\n" +
	"asset_code\x18\x01 \x01(\tR\tassetCode\x12!\n" +
	"\fasset_issuer\x18\x02 \x01(\tR\vassetIssuer\"o\n" +
	"\bTransfer\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12'\n" +
	"\x05asset\x18\x03 \x01(\v2\x11.stellar.v1.AssetR\x05asset\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\"W\n" +
	"\x04Mint\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12'\n" +
	"\x05asset\x18\x02 \x01(\v2\x11.stellar.v1.AssetR\x05asset\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"[\n" +
	"\x04Burn\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12'\n" +
	"\x05asset\x18\x02 \x01(\v2\x11.stellar.v1.AssetR\x05asset\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"_\n" +
	"\bClawback\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12'\n" +
	"\x05asset\x18\x02 \x01(\v2\x11.stellar.v1.AssetR\x05asset\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"Z\n" +
	"\x03Fee\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12'\n" +
	"\x05asset\x18\x02 \x01(\v2\x11.stellar.v1.AssetR\x05asset\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"\xb2\x02\n" +
	"\x12TokenTransferEvent\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".stellar.v1.TokenTransferEventMetaR\x04meta\x122\n" +
	"\btransfer\x18\x02 \x01(\v2\x14.stellar.v1.TransferH\x00R\btransfer\x12&\n" +
	"\x04mint\x18\x03 \x01(\v2\x10.stellar.v1.MintH\x00R\x04mint\x12&\n" +
	"\x04burn\x18\x04 \x01(\v2\x10.stellar.v1.BurnH\x00R\x04burn\x122\n" +
	"\bclawback\x18\x05 \x01(\v2\x14.stellar.v1.ClawbackH\x00R\bclawback\x12#\n" +
	"\x03fee\x18\x06 \x01(\v2\x0f.stellar.v1.FeeH\x00R\x03feeB\a\n" +
	"\x05event\"L\n" +
	"\x12TokenTransferBatch\x126\n" +
	"\x06events\x18\x01 \x03(\v2\x1e.stellar.v1.TokenTransferEventR\x06eventsBSZQgithub.com/withObsrvr/flowctl-token-transfer-processor/proto/stellar/v1;stellarv1b\x06proto3"

var (
	file_stellar_v1_token_transfers_proto_rawDescOnce sync.Once
	file_stellar_v1_token_transfers_proto_rawDescData []byte
)

func file_stellar_v1_token_transfers_proto_rawDescGZIP() []byte {
	file_stellar_v1_token_transfers_proto_rawDescOnce.Do(func() {
		file_stellar_v1_token_transfers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stellar_v1_token_transfers_proto_rawDesc), len(file_stellar_v1_token_transfers_proto_rawDesc)))
	})
	return file_stellar_v1_token_transfers_proto_rawDescData
}

var file_stellar_v1_token_transfers_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_stellar_v1_token_transfers_proto_goTypes = []any{
	(*TokenTransferEventMeta)(nil), // 0: stellar.v1.TokenTransferEventMeta
	(*Asset)(nil),                  // 1: stellar.v1.Asset
	(*IssuedAsset)(nil),            // 2: stellar.v1.IssuedAsset
	(*Transfer)(nil),               // 3: stellar.v1.Transfer
	(*Mint)(nil),                   // 4: stellar.v1.Mint
	(*Burn)(nil),                   // 5: stellar.v1.Burn
	(*Clawback)(nil),               // 6: stellar.v1.Clawback
	(*Fee)(nil),                    // 7: stellar.v1.Fee
	(*TokenTransferEvent)(nil),     // 8: stellar.v1.TokenTransferEvent
	(*TokenTransferBatch)(nil),     // 9: stellar.v1.TokenTransferBatch
	(*timestamppb.Timestamp)(nil),  // 10: google.protobuf.Timestamp
}
var file_stellar_v1_token_transfers_proto_depIdxs = []int32{
	10, // 0: stellar.v1.TokenTransferEventMeta.closed_at:type_name -> google.protobuf.Timestamp
	2,  // 1: stellar.v1.Asset.issued:type_name -> stellar.v1.IssuedAsset
	1,  // 2: stellar.v1.Transfer.asset:type_name -> stellar.v1.Asset
	1,  // 3: stellar.v1.Mint.asset:type_name -> stellar.v1.Asset
	1,  // 4: stellar.v1.Burn.asset:type_name -> stellar.v1.Asset
	1,  // 5: stellar.v1.Clawback.asset:type_name -> stellar.v1.Asset
	1,  // 6: stellar.v1.Fee.asset:type_name -> stellar.v1.Asset
	0,  // 7: stellar.v1.TokenTransferEvent.meta:type_name -> stellar.v1.TokenTransferEventMeta
	3,  // 8: stellar.v1.TokenTransferEvent.transfer:type_name -> stellar.v1.Transfer
	4,  // 9: stellar.v1.TokenTransferEvent.mint:type_name -> stellar.v1.Mint
	5,  // 10: stellar.v1.TokenTransferEvent.burn:type_name -> stellar.v1.Burn
	6,  // 11: stellar.v1.TokenTransferEvent.clawback:type_name -> stellar.v1.Clawback
	7,  // 12: stellar.v1.TokenTransferEvent.fee:type_name -> stellar.v1.Fee
	8,  // 13: stellar.v1.TokenTransferBatch.events:type_name -> stellar.v1.TokenTransferEvent
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_stellar_v1_token_transfers_proto_init() }
func file_stellar_v1_token_transfers_proto_init() {
	if File_stellar_v1_token_transfers_proto != nil {
		return
	}
	file_stellar_v1_token_transfers_proto_msgTypes[0].OneofWrappers = []any{}
	file_stellar_v1_token_transfers_proto_msgTypes[1].OneofWrappers = []any{
		(*Asset_Native)(nil),
		(*Asset_Issued)(nil),
		(*Asset_ContractId)(nil),
	}
	file_stellar_v1_token_transfers_proto_msgTypes[8].OneofWrappers = []any{
		(*TokenTransferEvent_Transfer)(nil),
		(*TokenTransferEvent_Mint)(nil),
		(*TokenTransferEvent_Burn)(nil),
		(*TokenTransferEvent_Clawback)(nil),
		(*TokenTransferEvent_Fee)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stellar_v1_token_transfers_proto_rawDesc), len(file_stellar_v1_token_transfers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stellar_v1_token_transfers_proto_goTypes,
		DependencyIndexes: file_stellar_v1_token_transfers_proto_depIdxs,
		MessageInfos:      file_stellar_v1_token_transfers_proto_msgTypes,
	}.Build()
	File_stellar_v1_token_transfers_proto = out.File
	file_stellar_v1_token_transfers_proto_goTypes = nil
	file_stellar_v1_token_transfers_proto_depIdxs = nil
}
